#
# This playbook launches a terminal (MinTTY) on local laptop/PC and starts an OpenBMC 
# simulator using SSH on remote host for each request student 
#
# Invocation:
# ansible-playbook StartStudentObmc.yml -e "user=francois" -e "Term=mintty.exe"
#
# ToDo: 
#     * Better integration of the Terminal launch. I.e. modify Terminal position 
#
# Version 0.31 
#

# Kill the remote qemu-studentXX process if any,
# Create the Obmc Launch script
# Copy the Obmc qemu image

- hosts: OpenbmcsInFpLR4
  gather_facts: false

  tasks:
    - name: include vars
      include_vars: "InfraConfig.yml"

    - name: Kill qemu-{{Student}} process if any
      become: true
      become_method: sudo
      become_user: root

      command: pkill -f qemu-{{Student}}{{item}}
      ignore_errors: yes
      #no_log: true
      with_sequence: "{{myrange}}"

    - name: Create Obmc Launch script
      become: true
      become_method: sudo
      become_user: root
      copy: 
        content: |
                #!/bin/bash
                
                /usr/kits/VMs/OpenBMC/qemu-system-arm -m 512 -M palmetto-bmc \
                    -net nic,macaddr=C0:FF:EE:00:{{item}}:01,model=ftgmac100      \
                    -net user,id=netdev0,hostfwd=:{{ObmcHostIP}}:{{ForwardPortSsh + item|int}}-:22,hostfwd=::{{ForwardPortHttps + item|int }}-:443,hostname=qemu-{{Student}}{{item}} \
                    -drive file={{ObmcDir}}/{{Student}}{{item}}-{{ObmcQemuImage}},format=raw,if=mtd     \
                    -nographic
                
        dest: "{{ObmcDir}}/{{Student}}{{item}}-LaunchObmc.sh"
        mode: a+x
      with_sequence: "{{myrange}}"

    - name: Create Obmc qemu image
      become: true
      become_method: sudo
      become_user: root
      copy: 
          src: "{{ObmcDir}}/{{ObmcOriginalQemuImage}}"
          remote_src: yes
          dest: "{{ObmcDir}}/{{Student}}{{item}}-{{ObmcQemuImage}}"
      with_sequence: "{{myrange}}"



