---
# Global Variables
# Version 0.13 
#prefix: "/home"
#workshop: "WKSHP-RedfishOverview"
#ref: "student0"
# capacity corresponds the upper limit of the range
capacity: 100
myrange: 100-{{capacity}}
parse: "{{ myrange.split('-') }}"
start: "{{parse[0]}}"
end: "{% if parse|length > 1 %}{{parse[1]}}{% else %}{{start}}{% endif %}"
Student: "student"
#ForwardPortSsh: "{% if capacity > 100 %}22{% else %}222{% endif %}"
#ForwardPortHttps: "{% if capacity > 100 %}44{% else %}443{% endif %}"
ForwardPortSsh: 22000
ForwardPortHttps: 44000
UrlPrefix: "https://{{ inventory_hostname }}"
UrlApiPrefix: "https://{{ inventory_hostname }}/hub/api"

