---
STUDDIR: "{{ ansible_env.STUDDIR }}"
JUPPROC: "{{ ansible_env.JUPPROC }}"
JUPPRIV: "{{ ansible_env.JUPPRIV }}"
JUPNOBO: "{{ ansible_env.JUPNOBO }}"
JUPPRIVNOBO: "{{ JUPPRIV }}/notebooks"
SCRIPTDIR: "{{ JUPPROC }}/scripts"
ANSIBLEDIR: "{{ JUPPROC }}/ansible"
SCRIPTPRIVDIR: "{{ JUPPRIV }}/scripts"
ANSIBLEPRIVDIR: "{{ JUPPRIV }}/ansible"
SENDER: sender@example.com
JPHUB: /opt/jupyterhub
CLEAN: false
USERMIN: 1
USERMAX: 2000
GIDBASE: 2000
UIDBASE: 2000
VAULTPWD: VeryComplexPasswd1234!
SURVEYURL: TBD
SURVEYCHALURL: TBD
TEMPTOKEN: TokenToBeDefined
NOCHECKSSH: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
# Painful Brranding !!
BRANDING: "WoD Developer"
BRANDINGWOD: "WoD Developer"
BRANDINGLOGO: "![HPEDEVlogo](Pictures/hpe-dev-logo.png)"
BRANDINGURL: "https://wod.io"
