# Backend only
#
# UIDBASE is the offset used to create the Linux user account IDs
# Example when creating user 35 with UIDBASE of 2000, the uid created is 2035
#
UIDBASE: 2000
#
# GIDBASE is the offset used to create the Linux group IDs
# Example when creating user 35 with GIDBASE of 2000, the gid created is 2035
#
GIDBASE: 2000
#
# Setup CLEAN to true if you want all Linux & Jupyter user accounts to be removed before ansible check
#
CLEAN: false
#
# VAULTPWD is the passwd used to manage the ansible vault
#
VAULTPWD: VeryComplexPasswd1234!
#
# NOCHECKSSH are ssh options used to dialog with appliances
# By default avoid checking Host keys and Host file as they may change on a regular base
#
NOCHECKSSH: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
#
# These variables are located lower in the ansible tree to allow different values required for different backends while keeping a single frontend
#
# JPHUB  is the directory used to install the JupyterHub stack (a python venv)
#
JPHUB: /opt/jupyterhub
#
# Replace with a random one - TODO Do that automatically at install time
#
WODBETOKEN: 2c0246e2c8564dc6ac7b12c544b25d77
#
# In case we have a LDAP server to use, flag as such the corresponding workshops in the DB and use the following values:
#
WODLDAPSRVNAME: ldap.example.org
WODLDAPDMN: example.org
WODLDAPPWD: MotDePasseLDAPCompliquéAussi123!!!##
WODLDAPPORT: "389"
#
# For various existing public WoDs - needed. Adapt but do not remove !
#
SSHPORT-WKSHP-Docker101: 14101
SSHPORT-WKSHP-Podman101: xx
SSHPORT-WKSHP-Podman201: yy
SSHPORT-WKSHP-Ansible101: 16001
HTTPPORT-WKSHP-Docker101: 14151
HTTPPORT-WKSHP-Podman101: xyzz
HTTPPORT-WKSHP-Podman201: xyzz
HTTPPORT-WKSHP-Ansible101: 16051
HTTPPORT-WKSHP-Spark101: 17161
HTTPPORT-WKSHP-Concourse101: 19061
HTTPPORT-WKSHP-ML101: 18061
HTTPPORT-WKSHP-DataVisu101: 22161
HTTPPORT-WKSHP-Tensorflow101: 23161
TENSORFLOWPORT1-WKSHP-Tensorflow101: 20001
TENSORFLOWPORT2-WKSHP-Tensorflow101: 20031
CONCOURSEPORT-WKSHP-Concourse101: 19001
CONCOURSEPORT2-WKSHP-Concourse101: 19031
IP-WKSHP-DataVisu101: x.y.z.t
IP-WKSHP-Concourse101: x.y.z.t
IP-WKSHP-Docker101: x.y.z.t
IP-WKSHP-Podman101: x.y.z.t
IP-WKSHP-Ansible101: x.y.z.t
IP-WKSHP-Spark101: x.y.z.t
IP-WKSHP-ML101: x.y.z.t
IP-WKSHP-Tensorflow101: x.y.z.t
IP-WKSHP-StackStorm101: x.y.z.t
SPARKPORT-WKSHP-Spark101: 17101
SPARKPORT2-WKSHP-Spark101: 17131
MLPORT-WKSHP-ML101: 18101
MLPORT2-WKSHP-ML101: 18031
DATAVISUPORT1-WKSHP-DataVisu101: 22101
DATAVISUPORT2-WKSHP-DataVisu101: 22131
TENSORPORT2-WKSHP-Tensorflow101: 23131
#LLM
LLM101_API_KEY: "test-api"
LLM101_MODEL_NAME: "hugging-quants/Meta-Llama-3.1-8B-Instruct-AWQ-INT4"
LLM101_BASE_URL: "http://x.y.z.t:8000/v1"
