---
STDDIR: /student
STD0DIR: "{{ ansible_env.HOME }}/wod-notebooks"
JUPPROC: "{{ ansible_env.HOME }}/wod-backend"
SCRIPTDIR: "{{ JUPPROC }}/scripts"
JPHUB: /opt/jupyterhub
CLEAN: false
USERMIN: 1
USERMAX: 2000
GIDBASE: 2000
UIDBASE: 2000
VAULTPWD: VeryComplexPasswd1234!
SURVEYURL: TBD
SURVEYCHALURL: TBD
TEMPTOKEN: TokenToBeDefined
NOCHECKSSH: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
# Painful Brranding !!
BRANDING: "WoD Developer"
BRANDINGWOD: "WoD Developer"
BRANDINGLOGO: "![HPEDEVlogo](Pictures/hpe-dev-logo.png)"
BRANDINGURL: "https://wod.io"
