---
STUDDIR: "{{ ansible_env.STUDDIR }}"
WODBEDIR: "{{ ansible_env.WODBEDIR }}"
WODPRIVDIR: "{{ ansible_env.WODPRIVDIR }}"
WODNOBO: "{{ ansible_env.WODNOBO }}"
WODSRVDIR: "{{ ansible_env.WODSRVDIR }}"
WODFEDIR: "{{ ansible_env.WODFEDIR }}"
WODPRIVNOBO: "{{ WODPRIVDIR }}/notebooks"
SCRIPTDIR: "{{ WODBEDIR }}/scripts"
ANSIBLEDIR: "{{ WODBEDIR }}/ansible"
SCRIPTPRIVDIR: "{{ WODPRIVDIR }}/scripts"
ANSIBLEPRIVDIR: "{{ WODPRIVDIR }}/ansible"
SENDER: sender@example.org
JPHUB: /opt/jupyterhub
CLEAN: false
USERMIN: 1
USERMAX: 20
GIDBASE: 2000
UIDBASE: 2000
VAULTPWD: VeryComplexPasswd1234!
SURVEYURL: TBD
SURVEYCHALURL: TBD
TEMPTOKEN: TokenToBeDefined
NOCHECKSSH: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
# Painful Brranding !!
BRANDING: "WoD Developer"
BRANDINGWOD: "WoD Developer"
BRANDINGLOGO: "![HPEDEVlogo](Pictures/hpe-dev-logo.png)"
BRANDINGURL: "https://wod.io"
