---

  - name: Disable Podman service
    register: service_stop
    become: yes
    become_user: root
    failed_when:
      - '"Could not find the requested service" not in service_stop.stdout'
      - service_stop.rc != 0
    systemd:
      state: stopped
      enabled: no
      name: podman
    ignore_errors: true

  - name: Disable Podman  socket
    register: service_stop
    become: yes
    become_user: root
    failed_when:
      - '"Could not find the requested service" not in service_stop.stdout'
      - service_stop.rc != 0
    systemd:
      state: stopped
      enabled: no
      name: podman.socket
    ignore_errors: true

  - name: Ensure there is no pre-existing podman.sock socket
    become: yes
    become_user: root
    file:
      path: /var/run/podman.sock
      state: absent

  - name: Ensure all required packages are installed
    become: yes
    become_user: root
    package:
      name:
      - podman
      - podman-compose
      state: present

  - name: Enable Podman service
    become: yes
    become_user: root
    systemd:
      state: started
      daemon_reload: yes
      enabled: yes
      name: podman

  - name: Ensure "{{ WODUSER }}" user belong to the Podman group
    become: yes
    become_user: root
    user:
      name: "{{ WODUSER }}"
      state: present
      append: yes
      groups: "podman"
