---
- name: Setup first the Docker context (packages, deps, ...)
  ansible.builtin.include_tasks: "{{ WODINSANSDIR }}/install_docker.yml"

- name: Ensure Linux students users belong to the docker group
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ 'student%s' | format(item) }}"
    state: present
    append: true
    groups: "docker"
  loop: "{{ range(WODAPPMIN | int, WODAPPMAX | int) | list }}"
