---

- name: Setup Playbook for WKSHP-Ansible101 appliance
  hosts: '{{ RTARGET }}'
  tasks:
    - name: Ensure all required packages are installed
      become: yes
      become_user: root
      package:
        pkg:
        - httpd

    - name: Setup firewalld TCP rules
      become: yes
      become_user: root
      ansible.posix.firewalld:
        port: "{{ item }}/tcp"
        zone: public
        permanent: yes
        state: enabled
      with_items:
        - "443"
        - "80"
        - "22"
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version >= "7"

    - name: Enable firewalld service
      become: yes
      become_user: root
      systemd:
        state: restarted
        daemon_reload: yes
        enabled: yes
        name: firewalld
      when:
        - ansible_distribution == "CentOS"
        - ansible_distribution_major_version >= "7"

    - name: Ensure that directory /var/www/student exists
      become: yes
      become_user: root
      file:
        path: "/var/www/student"
        state: directory
        owner: apache
        group: apache
        mode: 0711

    - name: Configure httpd for passwd usage
      become: yes
      become_user: root
      template:
        src: "{{ WODBEDIR }}/conf/WKSHP-Ansible101-httpd.conf.j2"
        dest: /etc/httpd/conf.d/ansible.conf
        owner: apache
        group: apache
        mode: 0644

    - name: Configure htpasswd
      become: yes
      become_user: root
      file:
        path: /etc/httpd/conf/htpasswd
        owner: apache
        group: apache
        mode: 0600
        state: touch
 
    - name: Ensure students web dir exist
      become: yes
      become_user: root
      file:
        path: "/var/www/student/{{ 'student%s' | format(item) }}"
        owner: apache
        group: apache
        mode: 0700
        state: directory
      loop: "{{ range( APPMIN|int, APPMAX|int + 1)|list }}"
 
    - name: Ensure students index.html file exist
      become: yes
      become_user: root
      template:
        src: "{{ WODBEDIR }}/conf/WKSHP-Ansible101-index.html.j2"
        dest: "/var/www/student/{{ 'student%s' | format(item) }}/index.html"
        owner: apache
        group: apache
        mode: 0600
      loop: "{{ range( APPMIN|int, APPMAX|int + 1)|list }}"

    - name: Enable httpd service
      become: yes
      become_user: root
      systemd:
        state: restarted
        daemon_reload: yes
        enabled: yes
        name: httpd
