- name: Install a base system
  include_tasks: "{{ ANSIBLEDIR }}/install_base_system.yml"

- name: Ensure that student directory exists
  become: yes
  become_user: root
  file:
    path: "{{ STUDDIR }}"
    state: directory
    owner: "{{ WODUSER }}"
    group: "{{ WODUSER }}"
    mode: 0711

- name: Use USERMIN for APPMIN if installing
  set_fact:
    APPMIN: "{{ USERMIN }}"
  when: APPMIN is not defined

- name: Use USERMAX for APPMAX if installing
  set_fact:
    APPMAX: "{{ USERMAX }}"
  when: APPMAX is not defined

- name: Remove Linux users and their home directory
  become: yes
  become_user: root
  user:
    name: "{{ 'student%s' | format(item) }}"
    state: absent
    remove: yes
    force: yes
  loop: "{{ range( APPMIN|int, APPMAX|int )|list }}"
  when: CLEAN|bool

- name: Ensure dedicated students groups exist
  become: yes
  become_user: root
  group:
    name: "{{ 'student%s' | format(item) }}"
    state: present
    gid: "{{ item + GIDBASE }}"
  loop: "{{ range( APPMIN|int, APPMAX|int )|list }}"
  when: LDAPSETUP != "1"

- name: Ensure Linux students users exists with their home dir
  become: yes
  become_user: root
  user:
    name: "{{ 'student%s' | format(item) }}"
    state: present
    create_home: true
    home: "{{ STUDDIR }}/{{ 'student%s' | format(item) }}"
    comment: "{{ 'student%s' | format(item) }}"
    shell: /bin/bash
    uid: "{{ item + UIDBASE }}"
    group: "{{ 'student%s' | format(item) }}"
  loop: "{{ range( APPMIN|int, APPMAX|int )|list }}"
  when: LDAPSETUP != "1"

- name: Disable SELinux for now as our students are non-standard
  become: yes
  become_user: root
  selinux:
    policy: targeted
    state: permissive
  when:
    - ansible_distribution == "CentOS" or ansible_distribution == "Rocky"

  # Do it in all cases LDAP or not as mode needs to be confirmed for ssh login
  # However, that doesn't seem to work on CentOS as dirs remains with mode 770
  # However, for rsync to work, we need to keep 770 !!
- name: Ensure Linux students users home dir exist with correct mode
  become: yes
  become_user: root
  file:
    path: "{{ STUDDIR }}/{{ 'student%s' | format(item) }}"
    owner: "{{ 'student%s' | format(item) }}"
    group: "{{ 'student%s' | format(item) }}"
    mode: '0750'
    state: directory
  loop: "{{ range( APPMIN|int, APPMAX|int )|list }}"
