---
  - name: Setup first the Docker context (packages, deps, ...)
    include_tasks: "{{ ANSIBLEDIR }}/install_docker.yml"

  - name: Ensure Linux students users belong to the docker group
    become: yes
    become_user: root
    user:
      name: "{{ 'student%s' | format(item) }}"
      state: present
      append: yes
      groups: "docker"
    loop: "{{ range( APPMIN|int, APPMAX|int )|list }}"

