# Playbook to generate instantiated reset scripts
# # All variables in upper case come from the procmail-action.sh script
- hosts: all
  gather_facts: true

  tasks: 
    - fail:
        msg: STDID variable is empty ! Fat fingers ?!?
      when: STDID is not defined

    - fail:
        msg: WORKSHOP variable is empty ! Fat fingers ?!?
      when: WORKSHOP is not defined

    - fail:
        msg: PBKDIR variable is empty ! Fat fingers ?!?
      when: PBKDIR is not defined

    - name: Deliver reset scripts as ansible template for variable expansion
      template:
        src: "{{ item }}"
        dest: "{{ item | basename | regex_replace('\.j2$') }}"
        mode: 0755
      with_fileglob: [ '{{ SCRIPTDIR }}/reset-*.sh.j2' ]
