- hosts: all
  gather_facts: true
  vars:
    IJAVAVER: "1.3.0"

  tasks: 
    - name: Ensure that required packages are installed for repo setup
      become: yes
      become_user: root
      apt:
        pkg:
        - apt-transport-https
        - curl
        - gnupg2

    - name: Update apt cache
      become: yes
      become_user: root
      apt:
        update_cache: yes
      changed_when: False

    - name: Add universe repository into sources list
      become: yes
      become_user: root
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security universe
        state: present

    - name: Add conda GPG Key to APT
      become: yes
      become_user: root
      apt_key:
        url: https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc
        state: present

    - name: Add conda APT repository
      become: yes
      become_user: root
      apt_repository:
        repo: deb [arch=amd64] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main
        state: present

    - name: Add K8s GPG Key to APT
      become: yes
      become_user: root
      apt_key:
        url: https://packages.cloud.google.com/apt/doc//apt-key.gpg.asc
        state: present

    - name: Add K8s APT repository
      become: yes
      become_user: root
      apt_repository:
        #repo: deb https://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release }} main
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Remove MicroSoft repo package
      become: yes
      become_user: root
      apt:
        pkg: 
        - packages-microsoft-prod.deb
        state: absent

    - name: Setup MicroSoft repo
      become: yes
      become_user: root
      apt:
        deb: https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/packages-microsoft-prod.deb

    - name: Update apt cache
      become: yes
      become_user: root
      apt:
        update_cache: yes
      changed_when: False

    - name: Ensure all required packages are installed
      become: yes
      become_user: root
      apt:
        pkg:
        - ansible 
        - python3 
        - python3-dev 
        - python3-pip 
        - python3-venv 
        - python3-jmespath 
        - python3-virtualenv 
        - python3-wheel
        - python3-nbconvert
        - python3-ipywidgets
        - git 
        - rsync 
        - acl 
        - curl 
        - wget 
        - bzip2 
        - firefox 
        - jq 
        - httpie 
        - apt-file 
        - moreutils 
        - net-tools 
        - ldap-utils
        - nodejs
        - npm
        - vim
        - pandoc
        - clang
        - cmake
        - default-jre
        - default-jdk
        - golang
        - texlive-xetex 
        - texlive-fonts-recommended 
        - texlive-latex-recommended
        - aspnetcore-runtime-3.1
        - aspnetcore-runtime-5.0
        - dotnet-runtime-3.1
        - dotnet-runtime-5.0
        - dotnet-sdk-3.1
        - dotnet-sdk-5.0
        - software-properties-common
        - gnupg2 
        - postfix 
        - procmail 
        - conda 
        - kubectl 
        - lld
        - libzmq3-dev
        - libgdiplus
        - libc6-dev
        - cargo
        - rustc

    - name: Ensure all required node.js packages are installed
      become: yes
      become_user: root
      community.general.npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - json
        - configurable-http-proxy

    - name: Remove a set of existing pip packages
      pip:
        name:
        - jupyterhub 
        - jupyterlab 
        - pyhpecfm==0.1.6
        - hpeOneView
        - ansible-kernel
        - bash_kernel
        - powershell_kernel
        - redfish
        state: absent
        virtualenv: "{{ JPHUB }}"
      when: CLEAN|bool
      ignore_errors: true

    - name: Remove directory "{{ JPHUB }}"
      become: yes
      become_user: root
      file:
        path: "{{ JPHUB }}"
        state: absent
      when: CLEAN|bool

    - name: Create directory "{{ JPHUB }}" if needed
      become: yes
      become_user: root
      file:
        path: "{{ JPHUB }}"
        state: directory
        owner: jupyter
        group: jupyter
        mode: 0751

    - name: Ensure all required pip packages are installed
      pip:
        name:
        - jupyterhub 
        - jupyterlab 
        - pyhpecfm==0.1.6
        - hpeOneView
        - ansible-kernel
        - bash_kernel
        - powershell_kernel
        - redfish
        state: present
        virtualenv: "{{ JPHUB }}"

    - name: Ensure Go kernel is installed
      shell: env GO111MODULE=off go get -d -u github.com/gopherdata/gophernotes && cd "{{ ansible_env.HOME }}/go/src/github.com/gopherdata/gophernotes" && env GO111MODULE=on go install && mkdir -p {{ JPHUB }}/share/jupyter/kernels/gophernotes && cp kernel/* {{ JPHUB }}/share/jupyter/kernels/gophernotes

    - name: Ensure /usr/local/bin is owned by jupyter
      become: yes
      become_user: root
      file:
        path: /usr/local/bin
        state: directory
        owner: jupyter
        group: jupyter
        mode: 0755

    - name: Make gophernotes available under /usr/local/bin
      copy:
        src: "{{ ansible_env.HOME }}/go/bin/gophernotes"
        dest: /usr/local/bin/gophernotes
        owner: jupyter
        group: jupyter
        mode: 0755

    - name: Make kernel_python available under /usr/local/bin
      copy:
        src: {{ SCRIPTDIR }}/kernel_python
        dest: /usr/local/bin/kernel_python
        owner: jupyter
        group: jupyter
        mode: 0755

    - name: Fix python kernel path to include virtualenv setup
      lineinfile:
        path: "{{ JPHUB }}//share/jupyter/kernels/python3/kernel.json"
        regexp: '^\s*"python",'
        line: '   "/usr/local/bin/kernel_python",'
        state: present

    - name: Ensure Rust kernel directory is installed
      file:
        path: "{{ JPHUB }}//share/jupyter/kernels/rust"
        state: directory
        owner: jupyter
        group: jupyter
        mode: 0751

    - name: Ensure Rust kernel is installed
      shell: . '{{ JPHUB }}/bin/activate' && {{ JUPPROC }}/evcxr_jupyter --install

    - name: Ensure Rust kernel files are installed
      copy:
        src: "{{ item }}"
        dest: "{{ JPHUB }}//share/jupyter/kernels/rust/{{ item | basename }}"
        owner: jupyter
        group: jupyter
        mode: 0644
      with_fileglob: [ '{{ ansible_env.HOME }}/.local/share/jupyter/kernels/rust/*' ]

    - name: Use new Rust kernel path
      lineinfile:
        path: "{{ JPHUB }}//share/jupyter/kernels/rust/kernel.json"
        regexp: '^\s*"{{ ansible_env.HOME }}/.cargo'
        line: '   "evcxr_jupyter",'
        state: present

    - name: Ensure Rust kernel is deployed
      copy:
        src: "{{ JUPPROC }}/evcxr_jupyter"
        dest: "/usr/local/bin/evcxr_jupyter"
        owner: jupyter
        group: jupyter
        mode: 0755

    - name: Extract iJava kernel
      unarchive:
        src: https://github.com/SpencerPark/IJava/releases/download/v{{ IJAVAVER }}/ijava-{{ IJAVAVER }}.zip
        dest: "{{ ansible_env.HOME }}"
        remote_src: yes

    - name: Ensure jupyter IJava kernel is installed
      shell: . '{{ JPHUB }}/bin/activate' && cd {{ ansible_env.HOME }} && python3 install.py --prefix={{ JPHUB }}

    - name: Ensure jupyter kernels are installed
      shell: . '{{ JPHUB }}/bin/activate' && python3 -m "{{ item }}.install" --prefix={{ JPHUB }}
      with_items:
        - bash_kernel
        - powershell_kernel
        - ansible_kernel
      changed_when: False

    - name: Test kubectl-hpecp presence
      command: ls /usr/local/bin/kubectl-hpecp
      register: kubectl_path
      ignore_errors: true
      changed_when: false

    - name: Ensure kubectl-hpecp is installed 
      file:
        src: "{{ JUPPROC }}/kubectl-hpecp-5-1-Linux"
        path: /usr/local/bin/kubectl-hpecp
        mode: 0755
      when: kubectl_path.rc != 0
    
    - name: Test pwsh presence
      command: ls /usr/local/bin/pwsh
      register: pwsh_path
      ignore_errors: true
      changed_when: false
    
    - name: Ensure powershell is installed through dotnet
      command: dotnet tool install --tool-path /usr/local/bin powershell
      when: pwsh_path.rc != 0
    
    - name: Ensure powershell scripts are installed
      command: "{{ SCRIPTDIR }}/install_PwshModules.sh"
    
    - name: Ensure that directory "{{ JPHUB }}/etc/jupyterhub" exists
      file:
        path: "{{ JPHUB }}/etc/jupyterhub"
        state: directory
        owner: jupyter
        group: jupyter
        mode: 0751

    - name: Remove jupyterhub configuration file
      file:
        path: "{{ JPHUB }}/etc/jupyterhub/jupyterhub_config.py"
        state: absent

    - name: Generate jupyterhub configuration
      command: "{{ JPHUB }}/bin/jupyterhub --generate-config"
      args:
        chdir: "{{ JPHUB }}/etc/jupyterhub/"

    - name: Adapt jupyterhub configuration file
      blockinfile:
        path: "{{ JPHUB }}/etc/jupyterhub/jupyterhub_config.py"
        block: |
          #####################################################################################
          c.Authenticator.admin_users = {'jupyter'}
          c.Authenticator.whitelist = {'jupyter'}
          c.Spawner.default_url = '/lab'
          c.JupyterHub.tornado_settings = {'cookie_options': {'expires_days': 0.17}}
          c.JupyterHub.shutdown_on_logout = True
          c.JupyterHub.redirect_to_server = True
          #####################################################################################

    - name: Copy jupyterhub service file 
      become: yes
      become_user: root
      copy:
        src: "{{ JUPPROC }}/jupyterhub.service"
        dest: /etc/systemd/system/jupyterhub.service

    - name: Enable Jupyterhub service 
      become: yes
      become_user: root
      systemd:
        state: started
        daemon_reload: yes
        enabled: yes
        name: jupyterhub

    - name: Test Jupyterhub token
      get_url: 
        url: "{{ JPHUBAPISRV }}/hub/api/users/jupyter"
        dest: "/tmp/result.{{ JPHUBTOKEN }}"
        headers:
          Authorization: "token {{ JPHUBTOKEN }}"
      register: answer
      ignore_errors: true
      changed_when: false

    - name: Remove temporary file
      file:
        path: "/tmp/result.{{ JPHUBTOKEN }}"
        state: absent

    - name: Build a new Jupyterhub token
      shell: . '{{ JPHUB }}/bin/activate' && '{{ JPHUB }}/bin/jupyterhub' token jupyter -f '{{ JPHUB }}/etc/jupyterhub/jupyterhub_config.py' | tail -1
      register: jup_token
      ignore_errors: true
      changed_when: false
      when: answer.status_code != 200

    - name: Fix Jupyter token in conf file
      lineinfile:
        path: "{{ JUPPROC }}/ansible-jupyter/group_vars/{{ PBKDIR }}"
        regexp: "^JPHUBTOKEN"
        line: "JPHUBTOKEN: {{ jup_token.stdout_lines[0] }}"
        state: present
      when: answer.status_code != 200

    - name: Enable postfix service 
      become: yes
      become_user: root
      systemd:
        state: started
        daemon_reload: yes
        enabled: yes
        name: postfix

    # For this to work, you need to have a key used in deploy key of the projects
    - name: Checkout notebooks from the jupyter-notebook git repo
      git:
        repo: git@github.com:HPEDevCom/jupyter-notebooks.git
        dest: "{{ ansible_env.HOME }}/student0"
        key_file: "{{ ansible_env.HOME }}/.ssh/id_student0"
