- hosts: localhost
  gather_facts: yes
  become: false
  tasks:
  - name: System details
    shell: echo '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}' > '{{ ansible_env.HOME }}/.mail/distrib'
